CREATE TABLE movies(
	movie_id SERIAL PRIMARY KEY,
	title VARCHAR(256),
	words_in_title VARCHAR(256),
	imdb_rating FLOAT,
	rating_count INT
);

CREATE TABLE BOOKS
(BOOKID VARCHAR(256) PRIMARY KEY,
 TITLE VARCHAR(1500) NOT NULL,
 AUTHORS VARCHAR(1500) NOT NULL,
 RATING FLOAT,
ISBN VARCHAR(20),
LANG_CODE VARCHAR(7),
RATINGS_COUNT INT);

CREATE TABLE TITLES(
ID VARCHAR(256) NOT NULL,
TITLE VARCHAR(1500));